### ISSUE TITLE
Enhanced Colaboration

### ISSUE THREAD

**Issue by wcervini** [lucascosti/bashrc#7]
Hi _Lucas_, I like your work. My name is Walter and I want collaborate with this project, just add a new branch with name **Develop**. I have a los of aliases for git for more functionality, and i use git flow too. I Recomend [Git Flow](https://github.com/nvie/gitflow), do your work more easy.

Take care, i'm wait your answer....

**Comment by lucascosti** [comment]
Hi Walter, thanks for the interest! This repo is mainly just for storing and sharing my own personal `.bashrc` file, and so I'm not really looking for additional collaboration (unless you want to do things like point out bugs or security issues, which of course is very welcome).

If you want to make changes for your own use, just create a fork/clone and go nuts! 😃
